name: Cypress Tests
on: [push, workflow_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
      - run: |
          npm ci
          cd example_app
          npx http-server &

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          wait-on: 'http://localhost:8080'

      - name: Merge reports
        run: |
          npm run get-report

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Reports
          path: cypress/reports